package com.shop.frames;

import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Turab Bajeer
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, (int) dim.getWidth(), (int) dim.getHeight());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        accountButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        orderDetailsButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        roleButton = new javax.swing.JButton();
        permissionButton = new javax.swing.JButton();
        assignPermissionButton = new javax.swing.JButton();
        purchaseButton = new javax.swing.JButton();
        purchaseDetailsButton = new javax.swing.JButton();
        purchaseTransactionHistory = new javax.swing.JButton();
        sellTransactionHistoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1109, 200));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/home_100px.png"))); // NOI18N
        jLabel1.setText("HOME");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/sign_out_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 399));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 299));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(4, 0, 10, 10));

        accountButton.setBackground(new java.awt.Color(52, 96, 95));
        accountButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accountButton.setForeground(new java.awt.Color(255, 255, 255));
        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/Merchant Account_50px.png"))); // NOI18N
        accountButton.setText("Account");
        accountButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        accountButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });
        jPanel7.add(accountButton);

        productButton.setBackground(new java.awt.Color(52, 96, 95));
        productButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productButton.setForeground(new java.awt.Color(255, 255, 255));
        productButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/product_50px.png"))); // NOI18N
        productButton.setText("Product");
        productButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });
        jPanel7.add(productButton);

        orderButton.setBackground(new java.awt.Color(52, 96, 95));
        orderButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderButton.setForeground(new java.awt.Color(255, 255, 255));
        orderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/Create Order_50px.png"))); // NOI18N
        orderButton.setText("Order");
        orderButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel7.add(orderButton);

        orderDetailsButton.setBackground(new java.awt.Color(52, 96, 95));
        orderDetailsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        orderDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/order_history_50px.png"))); // NOI18N
        orderDetailsButton.setText("Order Details");
        orderDetailsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        orderDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDetailsButtonActionPerformed(evt);
            }
        });
        jPanel7.add(orderDetailsButton);

        userButton.setBackground(new java.awt.Color(52, 96, 95));
        userButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userButton.setForeground(new java.awt.Color(255, 255, 255));
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/user_account_50px.png"))); // NOI18N
        userButton.setText("User");
        userButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel7.add(userButton);

        roleButton.setBackground(new java.awt.Color(52, 96, 95));
        roleButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roleButton.setForeground(new java.awt.Color(255, 255, 255));
        roleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/user_account_50px_1.png"))); // NOI18N
        roleButton.setText("Role");
        roleButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        roleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleButtonActionPerformed(evt);
            }
        });
        jPanel7.add(roleButton);

        permissionButton.setBackground(new java.awt.Color(52, 96, 95));
        permissionButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        permissionButton.setForeground(new java.awt.Color(255, 255, 255));
        permissionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/access_50px.png"))); // NOI18N
        permissionButton.setText("Permission");
        permissionButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        permissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionButtonActionPerformed(evt);
            }
        });
        jPanel7.add(permissionButton);

        assignPermissionButton.setBackground(new java.awt.Color(52, 96, 95));
        assignPermissionButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assignPermissionButton.setForeground(new java.awt.Color(255, 255, 255));
        assignPermissionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/admin_settings_male_50px.png"))); // NOI18N
        assignPermissionButton.setText("Role Permission");
        assignPermissionButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        assignPermissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPermissionButtonActionPerformed(evt);
            }
        });
        jPanel7.add(assignPermissionButton);

        purchaseButton.setBackground(new java.awt.Color(52, 96, 95));
        purchaseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        purchaseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/add_shopping_cart_50px.png"))); // NOI18N
        purchaseButton.setText("Purchase");
        purchaseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });
        jPanel7.add(purchaseButton);

        purchaseDetailsButton.setBackground(new java.awt.Color(52, 96, 95));
        purchaseDetailsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        purchaseDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/order_history_50px_1.png"))); // NOI18N
        purchaseDetailsButton.setText("Purchase Details");
        purchaseDetailsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        purchaseDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseDetailsButtonActionPerformed(evt);
            }
        });
        jPanel7.add(purchaseDetailsButton);

        purchaseTransactionHistory.setBackground(new java.awt.Color(52, 96, 95));
        purchaseTransactionHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseTransactionHistory.setForeground(new java.awt.Color(255, 255, 255));
        purchaseTransactionHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/Payment History_50px.png"))); // NOI18N
        purchaseTransactionHistory.setText("Purchae Transaction History");
        purchaseTransactionHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        purchaseTransactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTransactionHistoryActionPerformed(evt);
            }
        });
        jPanel7.add(purchaseTransactionHistory);

        sellTransactionHistoryButton.setBackground(new java.awt.Color(52, 96, 95));
        sellTransactionHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sellTransactionHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        sellTransactionHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/purchase_history_50px.png"))); // NOI18N
        sellTransactionHistoryButton.setText("Sell Transaction History");
        sellTransactionHistoryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        sellTransactionHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTransactionHistoryButtonActionPerformed(evt);
            }
        });
        jPanel7.add(sellTransactionHistoryButton);

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void permissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionButtonActionPerformed
       new PermissionFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_permissionButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        new AccountFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountButtonActionPerformed

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed
        new ProductFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        new NewOrderFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderButtonActionPerformed

    private void orderDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDetailsButtonActionPerformed
       new OrderDetailsFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_orderDetailsButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        new UserFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userButtonActionPerformed

    private void roleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleButtonActionPerformed
        new RoleFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_roleButtonActionPerformed

    private void assignPermissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPermissionButtonActionPerformed
        new AssignPermissionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assignPermissionButtonActionPerformed

    private void sellTransactionHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTransactionHistoryButtonActionPerformed
        new SellTransactionHistoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sellTransactionHistoryButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        new NewPurchaseFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void purchaseDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseDetailsButtonActionPerformed

        new PurchaseDetailsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_purchaseDetailsButtonActionPerformed

    private void purchaseTransactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTransactionHistoryActionPerformed
        new PurchaseTransactionHistoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_purchaseTransactionHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JButton assignPermissionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton orderDetailsButton;
    private javax.swing.JButton permissionButton;
    private javax.swing.JButton productButton;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JButton purchaseDetailsButton;
    private javax.swing.JButton purchaseTransactionHistory;
    private javax.swing.JButton roleButton;
    private javax.swing.JButton sellTransactionHistoryButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
