/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shop.frames;

import com.shop.DAO.CategoryDAO;
import com.shop.DAO.ProductDAO;
import com.shop.DAO.PurchaseDAO;
import com.shop.DAO.PurchaseDetailsDAO;
import com.shop.DAO.VendorDAO;
import com.shop.DAOImpl.CategoryDAOImpl;
import com.shop.DAOImpl.OrderDetailsDAOImpl;
import com.shop.DAOImpl.ProductDAOImpl;
import com.shop.DAOImpl.PurchaseDAOImpl;
import com.shop.DAOImpl.PurchaseDetailsDAOImpl;
import com.shop.DAOImpl.VendorDAOImpl;
import static com.shop.frames.NewOrderFrame.generateOrderCode;
import com.shop.model.Category;
import com.shop.model.Order;
import com.shop.model.Product;
import com.shop.model.Purchase;
import com.shop.model.PurchaseDetails;
import com.shop.model.Vendor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Turab Bajeer
 */
public class NewPurchaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewOrder
     */
    Object columns[] = {"ID", "Product", "Order Code", "Selling Price", "Quantity", "Total", "Created Date", "Created By", "Modified Date", "Modified By"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);

    public NewPurchaseFrame() {
        initComponents();

        purchasedItemsTable.setRowHeight(30);
        JTableHeader header = purchasedItemsTable.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", Font.BOLD, 16));

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, (int) dim.getWidth(), (int) dim.getHeight());
        setLocationRelativeTo(null);

        allProductsTable.setRowHeight(30);
        JTableHeader header1 = allProductsTable.getTableHeader();
        header1.setFont(new java.awt.Font("Tahoma", Font.BOLD, 16));
        
        purchaseDateField.setDate(new Date());
        currentPurchaseCode = generateOrderCode();
        purchaseCodeLabel.setText(currentPurchaseCode);

        purchasedItemsTable.setModel(model);

        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);

        fillProductCombo();
        fillVendorCombo();
        fillProductTable();
        fillOrderDetailsTable();
    }

    ProductDAO productDAOImpl = new ProductDAOImpl();
    PurchaseDAO purchaseDAOImpl = new PurchaseDAOImpl();
    PurchaseDetailsDAO purchaseDetailsDAOImpl = new PurchaseDetailsDAOImpl();
    CategoryDAO categoryDAOImpl = new CategoryDAOImpl();
    VendorDAO vendorDaoImpl = new VendorDAOImpl();
    PurchaseDetails pdt = null;
    Product product = null;
    static Purchase purchase = null;
    static Integer id = null;
    static Integer productId = null;
    static Integer vendorId = null;
    static Vendor vendor = null;
    Double purchasePrice = null;
    Integer quantity = null;
    Integer purchasedItemId = null;
    String purchaseCode = null;
    static Integer noOfTimeButtonClicked = 0;

    // current customer details
    String currentVendorName = null;
    String currentVendorAddress = null;
    String currentPurchaseCode = null;
    Purchase currentPurchase = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        purchaseCodeLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        productCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        purchaseDateField = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        purchasingPriceField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cancelPurchaseButton = new javax.swing.JButton();
        newPurchaserButton = new javax.swing.JButton();
        purchaseNowButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        vendorCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchasedItemsTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allProductsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/back_50px.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PURCHASE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 525));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PURCHASE");
        jPanel2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Purchase Code");

        purchaseCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        purchaseCodeLabel.setForeground(new java.awt.Color(153, 0, 51));
        purchaseCodeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Product");

        productCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Vendor");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Date");

        purchaseDateField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setText("Purchasing Price");

        purchasingPriceField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchasingPriceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        purchasingPriceField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        purchasingPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasingPriceFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Quantity");

        quantityField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Grand Total");

        grandTotal.setBackground(new java.awt.Color(255, 255, 255));
        grandTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grandTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grandTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cancelPurchaseButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelPurchaseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelPurchaseButton.setForeground(new java.awt.Color(0, 72, 54));
        cancelPurchaseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/cancel_order_20px.png"))); // NOI18N
        cancelPurchaseButton.setText("Cancel Purchase");
        cancelPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPurchaseButtonActionPerformed(evt);
            }
        });

        newPurchaserButton.setBackground(new java.awt.Color(255, 255, 255));
        newPurchaserButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newPurchaserButton.setForeground(new java.awt.Color(0, 72, 54));
        newPurchaserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/new Order_20px.png"))); // NOI18N
        newPurchaserButton.setText("New Purchase");
        newPurchaserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPurchaserButtonActionPerformed(evt);
            }
        });

        purchaseNowButton.setBackground(new java.awt.Color(255, 255, 255));
        purchaseNowButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        purchaseNowButton.setForeground(new java.awt.Color(0, 72, 54));
        purchaseNowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/order now_20px.png"))); // NOI18N
        purchaseNowButton.setText("Purchase Now");
        purchaseNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseNowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelPurchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseNowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPurchaserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newPurchaserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(purchaseNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(cancelPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 72, 54));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/add_20px.png"))); // NOI18N
        addButton.setText("Add Item");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 255, 255));
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(0, 72, 54));
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/Sync_20px.png"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 72, 54));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/Delete Bin_20px.png"))); // NOI18N
        deleteButton.setText("Delete Item");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 72, 54));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shop/resources/update_20px.png"))); // NOI18N
        updateButton.setText("Update Item");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        vendorCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vendorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchaseDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vendorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productCombo, 0, 312, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(purchaseCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantityField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchasingPriceField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vendorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(purchaseDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchasingPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {productCombo, vendorCombo});

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(719, 400));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PURCHASED ITEMS");
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        purchasedItemsTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        purchasedItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        purchasedItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasedItemsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchasedItemsTable);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Products");
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        allProductsTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        allProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(allProductsTable);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchasingPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasingPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchasingPriceFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        if (vendorCombo.getItemAt(0) == "" || quantityField.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Required details are not enough!", "Please fill all the fields!", 0);

        } else {

            noOfTimeButtonClicked += 1;
            currentVendorName = vendorCombo.getSelectedItem().toString();

            PurchaseDetails pdt = new PurchaseDetails();

            purchasePrice = Double.valueOf(purchasingPriceField.getText());

            quantity = Integer.valueOf(quantityField.getText());

            addItemToCart(noOfTimeButtonClicked);
            clearFields();
            grandTotal.setText(getGrandTotal().toString());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void productComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboActionPerformed

        if (productCombo.getSelectedIndex() == 0) {

        } else {
            String productName = productCombo.getSelectedItem().toString();
            productId = productDAOImpl.getProductIDByName(productName);

            Product p = productDAOImpl.getProductByID(productId);
            product = p;
            purchasingPriceField.setText(p.getPrice().toString());
        }
    }//GEN-LAST:event_productComboActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        clearFields();
        fillOrderDetailsTable();
        fillProductTable();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void purchaseNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseNowButtonActionPerformed
        if (purchasedItemsTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "You don't have any items to buy!, please add items.", "No items found", JOptionPane.WARNING_MESSAGE);
        } else {

            int r = addCartItemsToDatabase();
            if (r > 0) {
                System.out.println("Successfull");
            }
            currentPurchase = new Purchase();
            currentPurchase.setPurchaseCode(currentPurchaseCode);
            currentPurchase.setPurchaseDate(new Date());
            currentPurchase.setGrandTotal(getGrandTotal());
            currentPurchase.setVendor(vendor);
            currentPurchase.setPurchaseDate(new Date());
            currentPurchase.setCreatedDate(new Date());
            currentPurchase.setCreatedBy(0);

            purchase = currentPurchase;

            int result = purchaseDAOImpl.addPurchase(currentPurchase);

            if (result > 0) {
                
                new PurchasePaymentDialog(null, true).setVisible(true);
                JOptionPane.showMessageDialog(null, "Purchase Successfull!");
                currentPurchaseCode = generateOrderCode();
                purchaseCodeLabel.setText(currentPurchaseCode);

                new NewPurchaseFrame().setVisible(true);
                this.dispose();
                fillOrderDetailsTable();
                fillProductTable();
                clearFields();
                grandTotal.setText(getGrandTotal().toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error in Order", "Error", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_purchaseNowButtonActionPerformed

    private void newPurchaserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPurchaserButtonActionPerformed
        currentPurchaseCode = generateOrderCode();
        purchaseCodeLabel.setText(currentPurchaseCode);

        fillOrderDetailsTable();
        fillProductTable();
        fillProductCombo();
    }//GEN-LAST:event_newPurchaserButtonActionPerformed

    private void purchasedItemsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedItemsTableMouseClicked
        purchasedItemId = (Integer) purchasedItemsTable.getValueAt(purchasedItemsTable.getSelectedRow(), 0);

        if (purchasedItemId != null) {

            updateButton.setEnabled(true);
            deleteButton.setEnabled(true);

            PurchaseDetails purchaseDetails = purchaseDetailsDAOImpl.getPurchaseDetailsByID(purchasedItemId);
            Product p = productDAOImpl.getProductByID(purchaseDetails.getProduct().getProductID());

            productCombo.setSelectedItem(p.getProductName());
            purchasingPriceField.setText(purchaseDetails.getPurchasePrice().toString());
            quantityField.setText(purchaseDetails.getQuantity().toString());
            vendorCombo.setSelectedItem(currentVendorName);

            updateButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }
    }//GEN-LAST:event_purchasedItemsTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
//        if (customerField.getText().equals("") || addressField.getText().equals("") || quantityField.getText().equals("")) {
//
//            JOptionPane.showMessageDialog(null, "Required details are not enough!", "Please fill all the fields!", 0);
//
//        } else {
//
//            currentCustomerName = customerField.getText().toString();
//            currentCustomerAddress = addressField.getText().toString();
//
//            OrderDetails odt = orderDetailsDAOImpl.getOrderDetailsByID(orderedItemId);
//            int previousQuantity = odt.getQuantity();
//
//            sellingPrice = Double.valueOf(purchasingPriceField.getText());
//            quantity = Integer.valueOf(quantityField.getText());
//
//            odt.setProduct(product);
//            odt.setSellingPrice(sellingPrice);
//            odt.setQuantity(quantity);
//            odt.setTotal(sellingPrice * quantity);
//            odt.setModifiedDate(new Date());
//            odt.setModifiedBy(0);
//
//            int result2 = orderDetailsDAOImpl.updateOrderDetails(odt);
//
//            if (previousQuantity > quantity) {
//                int newQuantity = previousQuantity - quantity;
//                int result = productDAOImpl.plusProduct(product, newQuantity);
//            } else if (quantity > previousQuantity) {
//
//                int newQuantity = quantity - previousQuantity;
//                int result = productDAOImpl.reduceProduct(product, newQuantity);
//            } else if (quantity == previousQuantity) {
//
//                int newQuantity = previousQuantity - quantity;
//                int result = productDAOImpl.reduceProduct(product, newQuantity);
//            }
//            if (result2 > 0) {
//                JOptionPane.showMessageDialog(null, "Item updated!");
//                orderCode = generateOrderCode();
//                fillOrderDetailsTable();
//                fillProductTable();
//                clearFields();
//                grandTotal.setText(getGrandTotal().toString());
//            } else {
//                JOptionPane.showMessageDialog(null, "Error in Order", "Error", JOptionPane.ERROR_MESSAGE);
//
//            }
//
//        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
//        if (vendorCombo.getItemAt(0) == "" || quantityField.getText().equals("")) {
//
//            JOptionPane.showMessageDialog(null, "Required details are not enough!", "Please fill all the fields!", 0);
//
//        } else {
//
//            OrderDetails odt = orderDetailsDAOImpl.getOrderDetailsByID(orderedItemId);
//            int previousQuantity = odt.getQuantity();
//
//            quantity = Integer.valueOf(quantityField.getText());
//
//            int result2 = orderDetailsDAOImpl.deleteOrderDetails(orderedItemId);
//            int result = productDAOImpl.plusProduct(product, previousQuantity);
//
//            if (result2 > 0) {
//                JOptionPane.showMessageDialog(null, "Item removed");
//                orderCode = generateOrderCode();
//
//                model.removeRow(purchasedItemsTable.getSelectedRow());
//                purchasedItemsTable.clearSelection();
//                fillOrderDetailsTable();
//                fillProductTable();
//                clearFields();
//                grandTotal.setText(getGrandTotal().toString());
//            } else {
//                JOptionPane.showMessageDialog(null, "Error in Order", "Error", JOptionPane.ERROR_MESSAGE);
//
//            }
//
//        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPurchaseButtonActionPerformed
//        if (purchasedItemsTable.getRowCount() == 0) {
//
//            JOptionPane.showMessageDialog(null, "Create Order to cancel", "Order not found!", JOptionPane.WARNING_MESSAGE);
//        } else if (purchasedItemsTable.getValueAt(purchasedItemsTable.getSelectedRow(), 0) == orderedItemId) {
//
//            OrderDetails odt = orderDetailsDAOImpl.getOrderDetailsByID(orderedItemId);
//            int previousQuantity = odt.getQuantity();
//
//            quantity = Integer.valueOf(quantityField.getText());
//
//            int result2 = purchaseDetailsDAOImpl.deletePurchaseDetails(purchasedItemId);
//            int result = productDAOImpl.plusProduct(product, previousQuantity);
//
//            if (result2 > 0) {
//                JOptionPane.showMessageDialog(null, "Order canceled successfully!");
//                purchaseCode = generateOrderCode();
//
//                model.removeRow(purchasedItemsTable.getSelectedRow());
//                purchasedItemsTable.clearSelection();
//                fillOrderDetailsTable();
//                fillProductTable();
//                clearFields();
//                grandTotal.setText(getGrandTotal().toString());
//            } else {
//                JOptionPane.showMessageDialog(null, "Error in Order Cancellation", "Error", JOptionPane.ERROR_MESSAGE);
//
//            }
//        }
    }//GEN-LAST:event_cancelPurchaseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vendorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorComboActionPerformed
        if (vendorCombo.getSelectedIndex() == 0) {

        } else {
            String VendorName = vendorCombo.getSelectedItem().toString();
            if(vendorCombo.getSelectedIndex()==0){
            }else{
            vendorId = vendorDaoImpl.getVendorIDByName(VendorName);

            vendor = vendorDaoImpl.getVendorByID(vendorId);
            }
        }
    }//GEN-LAST:event_vendorComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPurchaseFrame().setVisible(true);
            }
        });
    }

    public void fillProductTable() {

        Object columns[] = {"ID", "Product", "Category", "Price", "Quantity", "Remarks", "Created Date", "Created By", "Modified Date", "Modified By"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        List<Product> allProducts = productDAOImpl.getAllProduct();

        for (Product p : allProducts) {
            Category c = categoryDAOImpl.getCategoryByID(p.getCategory().getCategoryID());
            Object rowData[] = {p.getProductID(), p.getProductName(), c.getCategoryName(), p.getPrice(), p.getQuantity(), p.getRemarks(), p.getCreatedDate(), p.getCreatedBy(), p.getModifiedDate(), p.getModifiedBy()};

            model.addRow(rowData);
            allProductsTable.setModel(model);

        }
    }

    public void fillOrderDetailsTable() {

        model = new DefaultTableModel(columns, 0);
        Order ord = new Order();
        ord.setOrderCode(currentPurchaseCode);
        Purchase pur = new Purchase();
        pur.setPurchaseCode(currentPurchaseCode);
        List<PurchaseDetails> allDetailses = purchaseDetailsDAOImpl.getAllDetailsOf(pur);

        for (PurchaseDetails pdt : allDetailses) {

            Product p = productDAOImpl.getProductByID(pdt.getProduct().getProductID());

            Object rowData[] = {pdt.getPurchaseDetailsID(), p.getProductName(), pdt.getPurchasePrice(), pdt.getQuantity(), pdt.getTotal(), pdt.getCreatedDate(), pdt.getCreatedBy(), pdt.getModifiedDate(), pdt.getModifiedBy()};

            model.addRow(rowData);
            purchasedItemsTable.setModel(model);

        }
    }

    public void clearFields() {

        productCombo.setSelectedIndex(0);
        purchasingPriceField.setText(null);
        quantityField.setText(null);

        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }

    static public String generatePurchaseCode() {

        String Capital_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String numbers = "0123456789";

        // Using random method 
        Random rndm_method = new Random();

        String password = "";

        for (int i = 0; i < 6; i++) {
            // Use of charAt() method : to get character value 
            // Use of nextInt() as it is scanning the value as int
            if (i == 2) {
                password += "-";
            }
            if (i == 0 || i == 1) {
                password += Capital_chars.charAt(rndm_method.nextInt(Capital_chars.length()));
            } else {
                password += numbers.charAt(rndm_method.nextInt(numbers.length()));
            }
        }
        return password;
    }

    public void fillProductCombo() {

        List<Product> allProducts = productDAOImpl.getAllProduct();
        productCombo.addItem("-- Select Product --");
        for (Product p : allProducts) {

            productCombo.addItem(p.getProductName());
        }
    }

    public void fillVendorCombo() {

        List<Vendor> allVendors = vendorDaoImpl.getAllVendor();
        vendorCombo.addItem("-- Select Vendor --");
        for (Vendor v : allVendors) {

            vendorCombo.addItem(v.getVendorName());
        }
    }

    public Double getGrandTotal() {
        double sum = 0.0;
        if (purchasedItemsTable.getModel() == null) {
        } else {

            for (int i = 0; i < purchasedItemsTable.getRowCount(); i++) {

                sum += Double.parseDouble(purchasedItemsTable.getValueAt(i, 5).toString());
            }

        }
        return sum;
    }

    public static Purchase getPurchase() {

        Vendor v = new Vendor();
        v.setVendorID(vendorId);
        purchase.setVendor(v);
        
        return purchase;
    }

    public void addItemToCart(int num) {

        Object rowData[] = {num, product.getProductName(), currentPurchaseCode, purchasePrice, quantity, quantity * purchasePrice, new Date(), "None", "None", "None"};

        model.addRow(rowData);
        purchasedItemsTable.setModel(model);
    }

    public Integer addCartItemsToDatabase() {
        int returnResult = 0;
        for (int i = 0; i < purchasedItemsTable.getRowCount(); i++) {

            PurchaseDetails pdt = new PurchaseDetails();

            Purchase pur = new Purchase();
            Product p = productDAOImpl.getProductByID(productDAOImpl.getProductIDByName(purchasedItemsTable.getValueAt(i, 1).toString()));

            Double sp = Double.valueOf(purchasedItemsTable.getValueAt(i, 3).toString());
            Integer qt = Integer.valueOf(purchasedItemsTable.getValueAt(i, 4).toString());

            pur.setPurchaseCode(purchasedItemsTable.getValueAt(i, 2).toString());
            pur.setCreatedDate(new Date());
            //System.out.println("Purchase Code: "+purchasedItemsTable.getValueAt(i, 2).toString());
            Date d = purchaseDateField.getDate();
            pdt.setPurchase(pur);
            pdt.setProduct(p);
            pdt.setPurchasePrice(sp);
            pdt.setQuantity(qt);
            pdt.setTotal(sp * qt);
            pdt.setCreatedDate(d);
            pdt.setCreatedBy(0);

            Integer result = purchaseDetailsDAOImpl.addPurchaseDetails(pdt);
            productDAOImpl.plusProduct(p, qt);
            if (result > 0) {
                
            }
        }
        return returnResult;
    }

    //pulic void updateOrder

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable allProductsTable;
    private javax.swing.JButton cancelPurchaseButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newPurchaserButton;
    private javax.swing.JComboBox<String> productCombo;
    private javax.swing.JLabel purchaseCodeLabel;
    private org.jdesktop.swingx.JXDatePicker purchaseDateField;
    private javax.swing.JButton purchaseNowButton;
    private javax.swing.JTable purchasedItemsTable;
    private javax.swing.JTextField purchasingPriceField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> vendorCombo;
    // End of variables declaration//GEN-END:variables
}
